language: python
python:
- '2.7'
- '3.3'
- pypy
deploy:
  provider: pypi
  user: toast38coza
  password:
    secure: pjZQU0fJhd9zG0q25R/YVA3wZTqnIdGs3wBMvzcGSkFFohza47m9lzdVs7c1IZZTFuWaN7EKzePcUht/RXlVcIxEHflfqKZpJwclzCNSzRzkK1WHSJbpwQi0ubTVXa+KdNVPBgp5Vhgl82OndO7CgWOcEBaLpJmcaYUNRbQG8V0=
  on:
    tags: true
    repo: TangentMicroServices/PythonClient
